### PR TITLE
Refactor/register route

### PR DESCRIPTION
**Pull request by agusbusta**
Update User model and /register endpoint for improved data handling
Modified the User model to change the 'email_verified' field from VARCHAR to BOOLEAN
Updated the /register endpoint to properly handle user creation with the new data type
Improved the unique token generation process for enhanced security
Adjusted the database migration to safely convert existing 'email_verified' data

### CODE REVIEW

**Comment by daviddflix** [comment]
## General Feedback

Here are my main observations:

**Token Generation:**
- The token should be created before committing the user to the database to reduce the possibility of creating a user without a token.

**Code Structure:**
- Move the generate_unique_short_token function to a separate utility module.

**Comment by agusbusta** [comment]
Ok it was fixed! let me know @daviddflix

**Comment by daviddflix** [comment]
**Feedback**

**Creation Status**: The status code for the creation process must be set to **201**.

**Returning Newly Created User:** While the client is correctly sending the user data, it's considered best practice to return the complete newly created user object rather than only a part of it. Currently, the implementation returns only the token **(response['auth_token'] = token).** Please modify this to return the full user data like so: **response['user'] = new_user.as_dict().** This approach provides a more comprehensive response to the client.

**User Schema Docstring:** The user schema previously included a docstring, similar to the other schemas. Please reintroduce the docstring to the user schema in config.py to maintain consistency and clarity across the codebase.

**Documentation Update:** Ensure that the documentation is updated to reflect the recent changes, including the updated return schema. This should be reflected in the Swagger JSON

Let me know if you need any assistance with these changes. Great work overall.

**Comment by agusbusta** [comment]
Done! let me know if there is something else to fix!

**Comment by daviddflix** [comment]
**Feedback: Handling Existing User Registration**

The current implementation of the /register endpoint does not account for the scenario where a user with the same **email or nickname** already exists in the system. This oversight could lead to duplicate user entries. Here are the suggested improvements:

**Check for Existing User:** Before creating a new user, we should check if a user with the same email or nickname already exists in the database.

**Unique Constraint:** Ensure that the database schema has unique constraints on the email and nickname fields of the User model.

**Error Handling:** Implement specific error handling for unique constraint violations.
Response for Existing User: Provide a clear response when attempting to register an existing user.

**Comment by daviddflix** [comment]
**Hey @agusbustadev,**

Everything looks great so far! However, there's one critical aspect we need to address: the management of sessions. Currently, we are using a global session, which isn't ideal as it can lead to potential conflicts and issues. To avoid this, each endpoint should have its own session management.

For the correct handling of session opening, commits, and closure, please refer to the guidelines provided in this document: [Session Management Guidelines](https://docs.google.com/document/d/1ysGEcKFlyCwlOFb4DVEft5xdsifm9bOeMNSVdAN5KcY/edit).

Let me know if you have any questions or need further assistance with this.

**Comment by agusbusta** [comment]
Session and lowercase unique token fixed! ready to review!

**Comment by daviddflix** [comment]
Hey @agusbusta 

I've reviewed the PR, and all the issues I pointed out have been fixed—great job! However, as discussed in yesterday's call, we need to ensure that all existing users in the database have a token. Since these users are already registered, we should define a default value in the user schema so that a default token is generated for all existing users during the migration.

Let me know if you have any questions!

**Review by daviddflix — APPROVED** [review]
This is good to go

**Pull request merged**
